import React from "react";
import Navbar from "../components/Navbar";
import { BsFillCartFill, BsFillHeartFill } from "react-icons/bs";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";
import styles from "../styles/Hackathons.module.css";

const Hackathons = ({ data }) => {
    return (
        <>


            <Head>
                <title>Seach | Hackathons</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="container-fluid">
                <Navbar />
            </div>


            <div className={styles.css_1df6fdn}>
                <h1 className={styles.css_1hsql8y}>
                    High School Hackathons <br className={styles.css_ys4k9c} /> in 2022
                </h1>
                <p className={styles.css_13z30eb}>
                    A curated list of high school hackathons with
                    <br className={styles.css_ys4k9c} /> 539 &nbsp;events in 24 &nbsp;states
                    + 22 &nbsp;countries.
                </p>
                <p className={styles.css_u21wlc}>
                    {" "}
                    Maintained by the{" "}
                    <a href="https://hackclub.com/" className={styles.css_cysksd}>
                        MLH
                    </a>{" "}
                    staff.
                </p>
            </div>

            <br /><br />
            <div className={`container-fluid ${styles.card_parent}`}>


                {data.map((item) => {
                    return (
                        <div key={item.id}>
                            {item.fields.banner &&
                                item.fields.logo &&
                                item.fields.start.split("T")[0].split("-")[0] > 2021 &&
                                item.fields.start.split("T")[0].split("-")[1] > 5 && (
                                    <div
                                        className={styles.hackathon_card}
                                        style={{
                                            backgroundImage: `linear-gradient(rgba(0,0,0,0) 0%, rgba(0,0,0,0.375) 75%), url('${item.fields.banner[0].url}')`,
                                            backgroundSize: "cover",
                                            backgroundPosition: "center",
                                        }}
                                        key={item.id}
                                    >
                                        <Image
                                            className={styles.card_logo}
                                            src={item.fields.logo[0].url}
                                            alt="Hellothere"
                                            width={50}
                                            height={50}
                                        />

                                        <div className={styles.text_div}>
                                            <h4> {item.fields.name} </h4>

                                            <h3>
                                                {" "}
                                                June {
                                                    item.fields.start.split("T")[0].split("-")[2]
                                                } - {item.fields.end.split("T")[0].split("-")[2]}{" "}
                                            </h3>
                                        </div>
                                    </div>
                                )}
                        </div>
                    );
                })}
            </div>

            {/* <button
                className="btn btn-warning"
                onClick={() => {
                    console.log(data);
                }}
            >
                Reveal
            </button> */}
        </>
    );
};

export async function getServerSideProps(context) {
    const res = await fetch(
        `https://api2.hackclub.com/v0.1/hackathons.hackclub.com/applications?select%7B%22filterByFormula%22:%22approved=1%22%7D`
    );
    const data = await res.json();

    // Pass data to the page via props
    return { props: { data } };
}

export default Hackathons;
